// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account/wachtwoord" | "/agenda" | "/agenda/[id]/bewerken" | "/dashboard" | "/instellingen" | "/klanten" | "/klanten/[id]" | "/klanten/[id]/behandelingen/[treatmentId]/bewerken" | "/klanten/[id]/bewerken" | "/klanten/[id]/print" | "/klanten/nieuwe" | "/login" | "/pakketten" | "/pakketten/[id]/bewerken" | "/platform" | "/platform/[id]" | "/platform/[id]/bewerken" | "/recepten" | "/recepten/[id]/bewerken" | "/team" | "/team/[id]/bewerken"
type AppRouteHandlerRoutes = "/api/export"
type PageRoutes = never
type LayoutRoutes = "/" | "/platform"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account/wachtwoord": {}
  "/agenda": {}
  "/agenda/[id]/bewerken": { "id": string; }
  "/api/export": {}
  "/dashboard": {}
  "/instellingen": {}
  "/klanten": {}
  "/klanten/[id]": { "id": string; }
  "/klanten/[id]/behandelingen/[treatmentId]/bewerken": { "id": string; "treatmentId": string; }
  "/klanten/[id]/bewerken": { "id": string; }
  "/klanten/[id]/print": { "id": string; }
  "/klanten/nieuwe": {}
  "/login": {}
  "/pakketten": {}
  "/pakketten/[id]/bewerken": { "id": string; }
  "/platform": {}
  "/platform/[id]": { "id": string; }
  "/platform/[id]/bewerken": { "id": string; }
  "/recepten": {}
  "/recepten/[id]/bewerken": { "id": string; }
  "/team": {}
  "/team/[id]/bewerken": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/platform": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
