// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(dashboard)/agenda/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agenda/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/agenda/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/agenda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agenda">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/agenda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/instellingen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instellingen">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/instellingen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/klanten/[id]/behandelingen/[treatmentId]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/klanten/[id]/behandelingen/[treatmentId]/bewerken">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/klanten/[id]/behandelingen/[treatmentId]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/klanten/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/klanten/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/klanten/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/klanten/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/klanten/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/klanten/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/klanten/[id]/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/klanten/[id]/print">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/klanten/[id]/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/klanten/nieuwe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/klanten/nieuwe">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/klanten/nieuwe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/klanten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/klanten">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/klanten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/pakketten/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pakketten/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/pakketten/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/pakketten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pakketten">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/pakketten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/recepten/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recepten/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/recepten/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/recepten/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recepten">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/recepten/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/team/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/team/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/wachtwoord/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/wachtwoord">> = Specific
  const handler = {} as typeof import("../../app/account/wachtwoord/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/[id]/bewerken/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[id]/bewerken">> = Specific
  const handler = {} as typeof import("../../app/platform/[id]/bewerken/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[id]">> = Specific
  const handler = {} as typeof import("../../app/platform/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform">> = Specific
  const handler = {} as typeof import("../../app/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export">> = Specific
  const handler = {} as typeof import("../../app/api/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/platform">> = Specific
  const handler = {} as typeof import("../../app/platform/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
